export const schoolsArray = [
  {
    "District Number": 39,
    "Display Name": "Magee Secondary",
    Address: "6360 MAPLE ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Westside Montessori Elementary School",
    Address: "4157 Oak St, 3396 Cambie St",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Vancouver Alternate School",
    Address: "1580 BROADWAY W",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Walter Moberly StrongStart Centre",
    Address: "1000 59TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "SD 39 DL Elementary",
    Address: "530 EAST 41ST AVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Eaton Arrowsmith School (Vancouver) Ltd",
    Address: "660C Leg-in-Boot Square",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Collingwood Neighbourhood School",
    Address: "3417 EUCLID AVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "John Henderson StrongStart Centre",
    Address: "451 53RD AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Anchor Point Montessori",
    Address: "PO BOX 32138, 1351 HORNBY ST",
    City: "RICHMOND",
  },
  {
    "District Number": 39,
    "Display Name": "Canada Royal Arts High School",
    Address: "896 8TH AVE W",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Columbia Academy",
    Address: "792 BEATTY ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Lowell High School",
    Address: "210-750 HAMILTON ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sino Bright School BC",
    Address: "300-328 WATER ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Qawsain Knowledge House",
    Address: "PO BOX 75044",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Columbia College",
    Address: "438 TERMINAL AVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "St Regis Secondary School",
    Address: "6145 Student Union Boulevard",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Elsie Roy Elementary",
    Address: "150 DRAKE ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "St. John's Academy",
    Address: "369 BOUNDARY RD",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Vancouver School Board Adult Ed",
    Address: "6010 FRASER ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "King George Secondary",
    Address: "1755 BARCLAY ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Kitsilano Secondary",
    Address: "2706 TRAFALGAR ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Britannia Community Secondary",
    Address: "1001 COTTON DR",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Lord Byng Secondary",
    Address: "3939 16TH AVE W",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Vancouver Technical Secondary",
    Address: "2600 BROADWAY E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Gladstone Secondary",
    Address: "4105 GLADSTONE ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir Winston Churchill Secondary",
    Address: "7055 HEATHER ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "David Thompson Secondary",
    Address: "1755 55TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Prince Of Wales Secondary",
    Address: "2250 EDDINGTON DR",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "University Hill Secondary",
    Address: "3228 ROSS DR",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir Guy Carleton Community Elementary",
    Address: "3250 KINGSWAY",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Admiral Seymour Elementary",
    Address: "1130 KEEFER ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "General Brock Elementary",
    Address: "4860 MAIN ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Lord Selkirk Elementary",
    Address: "1750 22ND AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Queen Alexandra Elementary",
    Address: "1300 BROADWAY E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Queen Mary Elementary",
    Address: "2000 TRIMBLE ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Emily Carr Elementary",
    Address: "4070 OAK ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "General Wolfe Elementary",
    Address: "4251 ONTARIO ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Lord Tennyson Elementary",
    Address: "1936 10TH AVE W",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Lord Strathcona Community Elementary",
    Address: "592 PENDER ST E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "John Oliver Secondary",
    Address: "530 41ST AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Templeton Secondary",
    Address: "727 TEMPLETON DR",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Killarney Secondary",
    Address: "6454 KILLARNEY ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir Charles Tupper Secondary",
    Address: "419 24TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Windermere Community Secondary",
    Address: "3155 27TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Eric Hamber Secondary",
    Address: "960 W. 33RD AVENUE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Lord Roberts Elementary",
    Address: "1100 BIDWELL ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "David Lloyd George Elementary",
    Address: "8370 CARTIER ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Simon Fraser Elementary",
    Address: "100 15TH AVE W",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "L'Ecole Bilingue Elementary",
    Address: "1166 W 14TH AVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Lord Nelson Elementary",
    Address: "1355 GARDEN DRIVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir Wilfred Grenfell Community",
    Address: "3323 WELLINGTON AVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Tecumseh Elementary",
    Address: "1850 41ST AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "General Gordon Elementary",
    Address: "2268 BAYSWATER ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Laura Secord Elementary",
    Address: "2500 LAKEWOOD DR",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Walter Moberly Elementary",
    Address: "1000 59TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Pierre Elliott Trudeau Elementary",
    Address: "449 62ND AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir Wm Van Horne Elementary",
    Address: "5855 ONTARIO ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "David Livingstone Elementary",
    Address: "315 23RD AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Hastings Community Elementary",
    Address: "2625 FRANKLIN ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "John Norquay Elementary",
    Address: "4710 SLOCAN ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "J.W. Sexsmith Community Elementary",
    Address: "7410 COLUMBIA ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir James Douglas Elementary",
    Address: "2150 BRIGADOON AVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir John Franklin Community",
    Address: "250S SKEENA ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir Sandford Fleming Elementary",
    Address: "6363 LANARK ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Lord Beaconsfield Elementary",
    Address: "3663 PENTICTON ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Lord Kitchener Elementary",
    Address: "3455 W. KING EDWARD AVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Shaughnessy Elementary",
    Address: "4250 MARGUERITE ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Renfrew Community Elementary",
    Address: "3315 22ND AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Queen Elizabeth Elementary",
    Address: "4102 16TH AVE W",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Trafalgar Elementary",
    Address: "4170 TRAFALGAR ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir Wilfrid Laurier Elementary",
    Address: "7350 LAUREL ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir William Osler Elementary",
    Address: "5970 SELKIRK ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "wək̓ʷan̓əs tə syaqʷəm Elementary School",
    Address: "1430 LILLOOET ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Thunderbird šxʷəxʷaʔəs Elementary",
    Address: "2325 CASSIAR ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Grandview ¿uuqinak’uuh Elementary",
    Address: "2055 WOODLAND DR",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Henry Hudson Elementary",
    Address: "1530 Maple Street",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Charles Dickens Elementary",
    Address: "1010 EAST 17TH AVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Bayview Community Elementary",
    Address: "2251 COLLINGWOOD ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Edith Cavell Elementary",
    Address: "500 20TH AVE W",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Maple Grove Elementary",
    Address: "6199 CYPRESS ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Quilchena Elementary",
    Address: "5300 MAPLE ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir Alexander Mackenzie Elementary",
    Address: "960 39TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Captain James Cook Elementary",
    Address: "3340 54TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Chief Maquinna Elementary",
    Address: "2684 2ND AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "David Oppenheimer Elementary",
    Address: "2421 SCARBORO AVE",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Sir Charles Kingsford-Smith",
    Address: "6901 ELLIOTT ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Carnarvon Community Elementary",
    Address: "3400 BALACLAVA ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Dr A R Lord Elementary",
    Address: "555 LILLOOET ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Waverley Elementary",
    Address: "6111 ELLIOTT ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "G T Cunningham Elementary",
    Address: "2330 37TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Nootka Community Elementary",
    Address: "3375 NOOTKA ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Tecumseh Annex",
    Address: "1551 37TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Dr George M Weir Elementary",
    Address: "2900 44TH AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "John Henderson Elementary",
    Address: "451 53RD AVE E",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Graham Bruce Community Elementary",
    Address: "3633 TANNER ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Queen Elizabeth Annex",
    Address: "4275 CROWN ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Tillicum Community Annex",
    Address: "2450 CAMBRIDGE ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 39,
    "Display Name": "Dr H N Maccorkindale Elementary",
    Address: "6100 BATTISON ST",
    City: "VANCOUVER",
  },
  {
    "District Number": 41,
    "Display Name": "Edmonds Community School",
    Address: "7651 18th Avenue",
    City: "BURNABY",
  },
];
